apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-default-gateway-config
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "16"
data:
  service: |
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: "letsencrypt-router-certs"
    spec:
      type: ClusterIP
