apiVersion: v1
kind: ConfigMap
metadata:
  name: gen-ai-aa-custom-model-endpoints
  namespace: sandbox
data:
  config.yaml: |
    providers:
      inference:
      - provider_id: endpoint-1
        provider_type: remote::openai
        config:
          base_url: https://api.openai.com/v1
          allowed_models:
          - gpt-5.4-mini
          custom_gen_ai:
            api_key:
              secretRef:
                name: endpoint-api-key-1
                key: api_key
      - provider_id: endpoint-2
        provider_type: remote::openai
        config:
          base_url: http://evolvewired.home.glroland.com:8080/v1
          allowed_models:
          - Qwen3-Coder-Next-GGUF
          custom_gen_ai:
            api_key:
              secretRef:
                name: endpoint-api-key-2
                key: api_key
    registered_resources:
      models:
      - provider_id: endpoint-1
        model_id: gpt-5.4-mini
        model_type: llm
        metadata:
          display_name: OpenAI [gpt-5.4-mini]
          custom_gen_ai:
            use_cases: chat, coding, tools
      - provider_id: endpoint-2
        model_id: Qwen3-Coder-Next-GGUF
        model_type: llm
        metadata:
          display_name: Evolve-Wired [Qwen3 Coder]
          custom_gen_ai:
            use_cases: coding
