kind: ConfigMap
apiVersion: v1
metadata:
 name: gen-ai-aa-mcp-servers
 namespace: redhat-ods-applications
data:
  Zabbix: |
   {
     "url": "http://zabbix.home.glroland.com:8080/mcp",
     "description": "initMAX's MCP Server for Zabbix.  This server exposes the entire Zabbix API as MCP tools — allowing any compatible AI assistant to query hosts, check problems, manage templates, acknowledge events, and perform any other Zabbix operation."
   }
  Incidents-Agent: |
   {
     "url": "https://incident-mcp-incident-mcp.apps.ocp.home.glroland.com/mcp",
     "description": "ServiceNow Incidents agent for interacting with Incidents and Config Item data in SNOW.  Searches, Incident Detail, Incident Work History, and the ability for appending comments to the work history are provided."
   }
  Ask-SQL: |
   {
     "url": "https://sqlchat-agent-asksql-sqlchat.apps.ocp.home.glroland.com/mcp",
     "description": "SQL Chat is a fork of Red Hat's Dataverse Agent, which provides natural language transaction to SQL for ad hoc queries against diverse data sources.  Leveraging a multi-tool approach, creative use of business guidance, and dynamic data dictionaries, SQL Chat makes it very easy to generate complex SQL and then execute against relational database sources."
   }
  Automate-IT-Research: |
   {
     "url": "https://automate-it-itops-research-agent-automate-it.apps.ocp.home.glroland.com/mcp",
     "description": "The Research Agent is responsible for analyzing knowledge and collatoral around a user's IT environment and standards and then providing helpful context to downstream tasks as it relates to the user's request.  The Research Agent is a component within Automate IT, which is a comprehensive platform for diagnosing where time is spent and issues occur across the IT landscape (using ServiceNow and spreadsheets as inputs), and then recommending automation to remediate and shorten the remediation gap."
   }
  Automate-IT-Plan: |
   {
     "url": "https://automate-it-itops-planning-agent-automate-it.apps.ocp.home.glroland.com/mcp",
     "description": "The Planning Agent takes high level requests and objectives from a user and then builds execution documentation that a human support engineer can take to implement the request in a high quality way.  The results of this agent can be used by other agents,  or entered into an organization's knowledge base, or stored in ServiceNow Problem Records for later use by support engineers.  The Planning Agent is a component within Automate IT, which is a comprehensive platform for diagnosing where time is spent and issues occur across the IT landscape (using ServiceNow and spreadsheets as inputs), and then recommending automation to remediate and shorten the remediation gap."
   }
  Automate-IT-Automate: |
   {
     "url": "https://automate-it-itops-automation-agent-automate-it.apps.ocp.home.glroland.com/mcp",
     "description": "The Automation Agent is responsible for writing taylored automation to implement a user request in the context of their IT environment.  This agent supports Ansible Playbooks, Bash Scripts, and PowerShell.  Contrary to most approaches it takes a planning and design step first, where a competing model is evaluating and criticizing the steps taken by the first to help achieve higher quality results.  The Automation Agent is a component within Automate IT, which is a comprehensive platform for diagnosing where time is spent and issues occur across the IT landscape (using ServiceNow and spreadsheets as inputs), and then recommending automation to remediate and shorten the remediation gap."
   }
  GitHub-MCP: |
   {
     "url": "https://api.githubcopilot.com/mcp",
     "description": "The GitHub MCP server enables exploration and interaction with repositories, code, and developer resources on GitHub. It provides programmatic access to repositories, issues, pull requests, and related project data, allowing automation and integration within development workflows. With this service, developers can query repositories, discover project metadata, and streamline code-related tasks through MCP-compatible tools."
   }
  Utilities: |
   {
     "url": "https://baseball-chatbot-agent-utilities-baseball-chatbot.apps.ocp.home.glroland.com/mcp",
     "description": "This is a utilities agent that was originally developed to support the Baseball Chatbot.  It provides helpful tools for getting the weather in a particular city as well as the temperature on a historic date."
   }
  MLB-Team: |
   {
     "url": "https://baseball-chatbot-agent-team-baseball-chatbot.apps.ocp.home.glroland.com/mcp",
     "description": "The Teams Agent is an MCP Server developed in support of the Baseball Chatbot.  It is able to look up various information around teams and players for Major League Baseball."
   }
  MLB-Game: |
   {
     "url": "https://baseball-chatbot-agent-game-baseball-chatbot.apps.ocp.home.glroland.com/mcp",
     "description": "This is a game metadata information support agent for the Baseball Chatbot.  It is able to determine when teams played, the final score, and various other data points."
   }
  OpenShift-MCP: |
   {
     "url": "http://openshift-mcp-server.sandbox.svc.cluster.local:8080/mcp",
     "description": "The OpenShift MCP Server provided by Red Hat that enables platform management teams to control and interact with the platform via natural language."
   }
